### ISSUE TITLE
居然还找到了作者的照片😂

### ISSUE THREAD

**Issue by hhllee** [OpenEthan/SMSBoom#109]
哈哈哈哈哈

**Comment by WhaleFell** [comment]
哼哼哼，这张有的憨。。当时随便弄了张上去，赶紧给本仙女删了吧，哼哼哼哼哼哼）

**Comment by demo2099** [comment]
真棒，笑啦

**Comment by hhllee** [comment]
> 哼哼哼，这张有点憨。。当时随便弄了张上去，赶紧给本仙女删了吧，哼哼哼哼哼哼）

现在的小朋友都这么厉害了吗  敲代码这么厉害哈哈哈哈哈
