### ISSUE TITLE
-

### ISSUE THREAD

**Issue by invoker233** [OpenEthan/SMSBoom#111]
-

**Comment by vxworkss** [comment]
说了啥？

**Comment by OpenEthan** [comment]
估計係激活咗你哋中共引以為豪嘅國家監控中心？ 你嘅手機上有冇装中共嘅監控程式？ 可以告訴一下你嘅所在地嗎？

**Comment by bernylinville** [comment]
> 使用者会被找上门?用户那么多。

不是使用者，是目标会被找上门

**Comment by humSuperman** [comment]
香港加油

**Comment by VinsonLaro** [comment]
我的评价是，不如赵弹

**Comment by Flysmallfish** [comment]
大陆的人通常手机内都会安装一款“国家反诈中心”（中共开发的，通常学校、工作单位等都会要求安装，作用是：打击、防范、治理电信网络诈骗等新型违法犯罪），本人没用过，但是该软件权限极高，可以截取电话、短信等隐私信息，还可以标注各种诈骗的电话号码，触发了监控，导致110找上门。

**Comment by JDDKCN** [comment]
woc还会这样吗，幸好测试的时候自己手机没装那个破软件

**Comment by fsf678** [comment]
> 

不知道欸，要看使用的接口里有没有诈骗网址这些

**Comment by nuxwe** [comment]
中共是这样的

**Comment by CN957** [comment]
咩啊 某得玩呀？

**Comment by ESUAdmin** [comment]
好抓，开香槟咯！是不是有的中国人一开始会用自己的手机号试试威力，就跟社工库查自己似的。唉，这过人的智商基本告别互联网了

**Comment by gougerlan** [comment]
自以為是 啐!

2023年4月30日 06:05，Nim Dause ***@***.******@***.***>> 写道：



好抓，开香槟咯！是不是有的中国人一开始会用自己的手机号试试威力，就跟社工库查自己似的。唉，这过人的智商基本告别互联网了

**Comment by wuchuangqk** [comment]
> 好抓，开香槟咯！是不是有的中国人一开始会用自己的手机号试试威力，就跟社工库查自己似的。唉，这过人的智商基本告别互联网了

那请问不先用自己手机号测试，怎么知道短信有没有发送成功

**Comment by Amy-White** [comment]
我手机被偷了都没人管，警哥管这种没业绩的小事？
