### ISSUE TITLE
电报群组被ban

### ISSUE THREAD

**Issue by Mrered** [OpenEthan/SMSBoom#142]
如图，电报群组被官方以传播色//情内容ban了![image](https://user-images.githubusercontent.com/34948506/187177499-12155ba1-c5a1-48ee-84af-f99a88b504dc.jpeg)

**Comment by OpenEthan** [comment]
@Mrered 离谱

**Comment by OpenEthan** [comment]
@Mrered 离谱

**Comment by Mrered** [comment]
@OpenEthan 雀食离谱，很好奇里面到底发啥了（狗头
