### ISSUE TITLE
可以更新接口，发送不成功

### ISSUE THREAD

**Issue by zxjsir-hub** [OpenEthan/SMSBoom#166]
❌  00:54:59,166 [ERROR] MainThread smsboom_EN:60 - proxies Failed to load
✔️  00:54:59,167 [SUCCESS] MainThread smsboom_EN:135 - No. 11Wave bombing begins！
✔️  00:54:59,167 [SUCCESS] MainThread smsboom_EN:135 - No. 12Wave bombing begins！
✔️  00:54:59,167 [SUCCESS] MainThread smsboom_EN:135 - No. 13Wave bombing begins！
✔️  00:54:59,167 [SUCCESS] MainThread smsboom_EN:135 - No. 14Wave bombing begins！
✔️  00:54:59,167 [SUCCESS] MainThread smsboom_EN:135 - No. 15Wave bombing begins！

**Comment by zzhouzhenyu** [comment]
怎么更新接口 接口都用不了
