### ISSUE TITLE
前面一切正常，怎么到了最后一步不行了

### ISSUE THREAD

**Issue by Tong1221** [OpenEthan/SMSBoom#177]

**Comment by sxkiss** [comment]
还不如用手机执行python smsboom.py  -t 60 - p  133****64365
手机运行是没问题

**Comment by Tong1221** [comment]
手机不会呀，手机的话怎么CMD






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenEthan/SMSBoom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月23日(星期天) 下午2:44
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [OpenEthan/SMSBoom] 前面一切正常，怎么到了最后一步不行了 (Issue #177)





 
还不如用手机执行python smsboom.py  -t 60 - p  133****64365
 手机运行是没问题

**Comment by sxkiss** [comment]
手机安装个termux  在安装环境python  运行脚本smsboom.py

**Comment by Tong1221** [comment]
谢大佬，大佬你肯定很厉害吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenEthan/SMSBoom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月23日(星期天) 下午2:48
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [OpenEthan/SMSBoom] 前面一切正常，怎么到了最后一步不行了 (Issue #177)





 
手机安装个termux  在安装环境python  运行脚本smsboom.py

**Comment by sxkiss** [comment]
![Screenshot_2022-10-23-08-54-45-968_com termux](https://user-images.githubusercontent.com/20202724/197378558-d1f3a5c4-2127-4946-bff1-c2cd7a40b686.jpg)

![Screenshot_2022-10-23-08-55-01-323_com termux](https://user-images.githubusercontent.com/20202724/197378567-689f3e7d-a714-41c0-a90d-494624db87dc.jpg)

**Comment by sxkiss** [comment]
python smsboom.py run -t 60 -p 133****64365

**Comment by YJ812** [comment]
兄弟怎操作的啊

**Comment by YJ812** [comment]
> 还不如用手机执行python smsboom.py -t 60 - p 133****64365
> 手机运行是没问题

手机怎么用啊
