### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Snowfly-Guo** [OpenEthan/SMSBoom#182]
![image](https://user-images.githubusercontent.com/79904577/200983879-c1be153e-dbfe-4f61-90d9-43143b5d9e23.png)

**Comment by Walnut-233** [comment]
https://github.com/OpenEthan/SMSBoom/issues/172#issuecomment-1283524458

**Comment by Snowfly-Guo** [comment]
> https://github.com/OpenEthan/SMSBoom/issues/172#issuecomment-1283524458

解决了，谢谢
