### ISSUE TITLE
一些问题!

### ISSUE THREAD

**Issue by huchase** [OpenEthan/SMSBoom#197]
api.json格式有问题, 必须使用例如vscode格式化后才能正常使用;

本人测试大部分(几乎是全部) 接口都已经失效

建议使用node.js重写 (狗头保命)

后期如果有需要and 有时间, 我会试着自己用 node.js 自己实现一个

**Comment by xtzml** [comment]
你写了吗

**Comment by chinajc** [comment]
蹲一手老哥

**Comment by OpenEthan** [comment]
wait in hope!
