### ISSUE TITLE
【GUI图形支持】给SMSBoom写了一个傻瓜式的图形界面。

### ISSUE THREAD

**Issue by JDDKCN** [OpenEthan/SMSBoom#217]
抱歉占用了一个lssues。我给SMSBoom写了个好用美观的GUI，传送门在这里：[SMSBoomGUI](https://github.com/JDDKCN/SMSBoomGUI)。
----
#### 该GUI目前支持的操作：
- 一次轰炸/多次轰炸（线程数量/轰炸次数/轰炸间隔可调）
- 一键升级接口
- 编辑代理以及代理模式运行
- 静默运行
- 自动取消系统代理（可选，防止运行出错）
- 更多功能还在开发中！
#### 虽然技术力不高，但也是我的一份心意了喵~
![Logo](https://raw.githubusercontent.com/JDDKCN/SMSBoomGUI/main/SMSBoomGUI-01.png)

**Comment by OpenEthan** [comment]
I think your program is fantastic! Very suitable for inexperienced users.Thx you for your contribution!

Can I write your GUI support program in the README?

**Comment by JDDKCN** [comment]
> I think your program is fantastic! Very suitable for inexperienced users.Thx you for your contribution!
> 
> Can I write your GUI support program in the README?

Of course, thank you!

**Comment by superzz7** [comment]
请问代理怎么设置  哪里找  格式是什么😂

**Comment by TC5234** [comment]
请问获取接口失败怎么弄啊，小白一个，
