### ISSUE TITLE
失效接口提交处

### ISSUE THREAD

**Issue by wJJh** [OpenEthan/SMSBoom#220]
若有失效或者不确定是否能用的接口可以统一提交到这里 本人为爬虫工程师 摸鱼的时候会去看看 比心比心:heart:

**Comment by wJJh** [comment]
结果测试发现许多接口都上了验证码防护 才有很多失败的 虽然不是不能破 不过数量一多导致成本增加了 比重新找裸接口成本高 (恼)

**Comment by jack52896** [comment]
大佬加油

**Comment by chinajc** [comment]
老哥加油可以v你3块喝个汽水。😁

**Comment by xx0114** [comment]
我有几万个接口，但不会转格式 怎么发给你

**Comment by wJJh** [comment]
> 我有几万个接口，但不会转格式 怎么发给你

发到这个邮箱里面把 xiao.yaodao@qq.com 感谢 有空的时候我会慢慢处理

**Comment by toooooop** [comment]
几万个接口？


王少华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenEthan/SMSBoom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月14日(星期二) 上午9:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [OpenEthan/SMSBoom] 失效接口提交处 (Issue #220)





  
我有几万个接口，但不会转格式 怎么发给你
  
发到这个邮箱里面把 ***@***.*** 感谢 有空的时候我会慢慢处理

**Comment by a7611818** [comment]
> 我有几万个接口，但不会转格式 怎么发给你

哥，能不能发我一份？我整理好格式就分享给你ybq_ybq@q

**Comment by gougerlan** [comment]
Hey  你们谁哪里有大量的接口?可否share一份出来供测试下?

2023年4月15日 07:37，a7611818 ***@***.******@***.***>> 写道：



我有几万个接口，但不会转格式 怎么发给你

***@***.***

**Comment by a7611818** [comment]
> 我有几万个接口，但不会转格式 怎么发给你

求分享，我如果能把接口引进去一定申请合并上去给大家一起用

**Comment by Marcel-Knotts** [comment]
唉，都联系不上仓库主，他的简介说私信告诉FB账号，却没看到私信入口😂

a7611818 ***@***.***>于2023年5月1日 周一20:38写道：

**Comment by Wuhou666** [comment]
> > 我有几万个接口，但不会转格式 怎么发给你
> 
> 兄弟可不可以发我一份[x8413951@gmail.com](mailto:x8413951@gmail.com)，我也来学学研究python

兄弟能不能发我一份3030923179@qq.com

**Comment by aolai666** [comment]
兄弟来一份2382153490@QQ.com
