### ISSUE TITLE
报错是为啥呢

### ISSUE THREAD

**Issue by monobo1989** [OpenEthan/SMSBoom#221]
20:13:42,005 [ERROR] ThreadPoolExecutor-0_37 req:72 - 请求失败_ssl.c:1108: The handshake operation timed out
❌  20:13:44,900 [ERROR] ThreadPoolExecutor-0_29 req:72 - 请求失败timed out

请问总出现报错是为啥？而且电脑总是咚咚的叫啊

**Comment by jack52896** [comment]
你的内容就是报错原因

**Comment by OpenEthan** [comment]
#200
