### ISSUE TITLE
新版 短信轰炸机

### ISSUE THREAD

**Issue by zhaoseq** [OpenEthan/SMSBoom#227]
https://wwfi.lanzouy.com/b00qnaqbc
密码:bz3g
新版 短信轰炸机

**Comment by JohnTitor5100** [comment]
是骗子，不要下载

**Comment by OpenEthan** [comment]
The security of third-party closed-source programs cannot be determined, so please do not download them!

**Comment by chinajc** [comment]
没有卡密玩毛啊？

**Comment by zhaoseq** [comment]
> 

app里面免费发两次卡密。。。随便逆向看源码。。有什么安全问题？

**Comment by zhaoseq** [comment]
> 是骗子，不要下载

傻逼哦 你自己看看免费没？另外里面有获取卡密方法
