### ISSUE TITLE
这个可以自己改一下  不难

### ISSUE THREAD

**Issue by karuiya** [OpenEthan/SMSBoom#230]
这个可以自己改一下  不难
怎么改教一下
_Originally posted by @KerryManson in https://github.com/OpenEthan/SMSBoom/issues/21#issuecomment-1144372160_

**Comment by KerryManson** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shijiediyishuaige** [comment]
求教如何更改

**Comment by KerryManson** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
