### ISSUE TITLE
@LKAJDFLKJALKJSAF 已经安排上了，暑假再搞咯

### ISSUE THREAD

**Issue by karuiya** [OpenEthan/SMSBoom#231]
怎么弄怎么弄，教一下哈哈哈     @LKAJDFLKJALKJSAF 已经安排上了，暑假再搞咯

_Originally posted by @WhaleFell in https://github.com/OpenEthan/SMSBoom/issues/45#issuecomment-1172062745_

**Comment by WhaleFell** [comment]
We are not sure of your intent in raising the issue, and we suspect that you are the cyber security police on the Chinese side so the issue is closed.

**Comment by OpenEthan** [comment]
We are not sure of your intent in raising the issue, and we suspect that you are the cyber security police on the Chinese side so the issue is closed.
