### ISSUE TITLE
别抑郁了，兴奋一下

### ISSUE THREAD

**Issue by lcvvvv** [OpenEthan/SMSBoom#24]
[1000+.txt](https://github.com/WhaleFell/SMSBoom/files/8801469/1000%2B.txt)

**Comment by weclont** [comment]
> [1000+.txt](https://github.com/WhaleFell/SMSBoom/files/8801469/1000%2B.txt)

刚刚试了一下里面的接口，感觉可用性不是很高啊

**Comment by KerryManson** [comment]
大部分都失效了

**Comment by KerryManson** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
