### ISSUE TITLE
一个支持定时任务的短信轰炸&短信测压Web应用 

### ISSUE THREAD

**Issue by ohnicemonday** [OpenEthan/SMSBoom#277]
✨ 一个支持定时任务的短信轰炸&短信测压Web应用 

基于当前项目的应用，详情在下方**链接仓库**

<del>https://github.com/ohnicemonday/smsboom</del>

**Comment by Lemon109** [comment]
404了有没有新的

**Comment by ohnicemonday** [comment]
> 404了有没有新的

如果需要购买，联系ohnicemonday@outlook.com
