### ISSUE TITLE
Error: Value must be an iterable.值必须是可迭代的

### ISSUE THREAD

**Issue by yccshh** [OpenEthan/SMSBoom#301]
运行python smsboom.py后 
出现”phone："
输入号码后报错Error: Value must be an iterable.
已确认过log.py文件中已删除level.icon

**Comment by juzishazhou** [comment]
解决了吗？我也这问题

**Comment by yccshh** [comment]
> 解决了吗？我也这问题

解决了，用教程下面的命令 直接在命令里面传入号码就ok了

**Comment by juzishazhou** [comment]
是#207吗？

**Comment by juzishazhou** [comment]
> > 解决了吗？我也这问题
> 
> 解决了，用教程下面的命令 直接在命令里面传入号码就ok了

那你有没有遇到“读取接口出错！正在重新下载接口数据”的情况？

**Comment by yccshh** [comment]
> > > 解决了吗？我也这问题
> > 
> > 
> > 解决了，用教程下面的命令 直接在命令里面传入号码就ok了
> 
> 那你有没有遇到“读取接口出错！正在重新下载接口数据”的情况？

手动替换api.json文件
