### ISSUE TITLE
smsboom_pyinstall.exe 的 -f 参数无法使用

### ISSUE THREAD

**Issue by TianbaoBai** [OpenEthan/SMSBoom#51]
.\smsboom_pyinstall.exe run -t 64 -p 15900000000 -f 10
Usage: smsboom_pyinstall.exe run [OPTIONS]
Try 'smsboom_pyinstall.exe run --help' for help.

Error: No such option: -f

**Comment by fwder** [comment]
@TianbaoBai 落落编译个Windows的Release吧（

**Comment by fwder** [comment]
已解决, 参考 #58 .

**Comment by OpenEthan** [comment]
而家有編譯新嘅EXE，https://github.com/OpenEthan/SMSBoom/releases/tag/main，多謝大家支持
