### ISSUE TITLE
看见这个项目真的是眉头一皱，如果5年后你再回过头来看你这段经历想必会有不同的思考。

### ISSUE THREAD

**Issue by LgnMs** [OpenEthan/SMSBoom#85]

**Comment by zoudingyi** [comment]
哈哈哈哈 别人还是个孩子

**Comment by cancundeyingzi** [comment]
思考个捶，你大学毕业去看一下高中时候的事情，你就不是眉头一皱这么简单了。

**Comment by breathiness** [comment]
高情商:“不同的思考”
低情商:“社死体验”

**Comment by OpenEthan** [comment]
原作者以後睇到自己高中寫嘅代碼可能要【社死】，所以將倉庫轉移畀我咗哈哈哈。

**Comment by iceBear67** [comment]
昨天还看着维护者是 WhaleFall 呢今天就变成 "OpenEthan" 了，一看 commit 还是 WhaleFall 在提交

刚注册一天不到，又改 README 又改个人信息看着都累哈:laughing:

**Comment by qiuquanwu** [comment]
> 原作者以後睇到自己高中寫嘅代碼可能要【社死】，所以將倉庫轉移畀我咗哈哈哈。

你是港独？
