### ISSUE TITLE
docker可以一键直接拉取了

### ISSUE THREAD

**Issue by lanqsh** [OpenEthan/SMSBoom#98]
docker run --rm lanqsh/smsboom + 参数

示例:
```
docker run --rm lanqsh/smsboom run -t 1 -p {PHONE} -i 1
```
![image](https://user-images.githubusercontent.com/12372700/177906133-a5e9bfba-7ec7-4d15-8f7e-60dcb8de744a.png)

**Comment by 382982408** [comment]
docker 在拉取后卡死:
![image](https://user-images.githubusercontent.com/29687145/178091455-291caee2-d0f2-419a-b00b-d3d062ff848c.png)
